#!/bin/bash
#
# ssh into a machine and automatically set the background
# color of Mac OS X Terminal depending on the hostname.
#
# Installation:
# 1. Save this script to /some/bin/ssh-host-color
# 2. chmod 755 /some/bin/ssh-host-color
# 3. alias ssh=/some/bin/ssh-host-color
# 4. Configure your host colors below.


set_term_bgcolor() {
   local R=$1
   local G=$2
   local B=$3
   /usr/bin/osascript <<EOF
tell application "iTerm"
  tell the current terminal
    tell the current session
      set the background color to {$(($R*65535/255)), $(($G*65535/255)), $(($B*65535/255))}
    end tell
  end tell
end tell
EOF
}

# Host-specific background colors.
if [[ "$@" =~ db001 ]]; then
   set_term_bgcolor 80 0 0
elif [[ "$@" =~ db002 ]]; then
   set_term_bgcolor 0 80 0
fi

ssh $@

# Default background color.
set_term_bgcolor 0 0 0
