#! /bin/bash

repo=`git remote show -n origin|perl -nle 'print $1 if /Fetch URL: .*:(.*).git/'`
if [[ "$repo" == "" ]]
then
  exit
fi
if [[ -e "$1" ]]
then
  branch=$(git symbolic-ref -q HEAD)
  branch=${branch##refs/heads/}
  url=http://github.com/$repo/commits/$branch/$1
elif [[ "$1" != "" ]]
then
  url=http://github.com/$repo/commit/$1
else
  url=http://github.com/$repo
fi
echo "Opening $url..."
open $url
