#! /usr/bin/python2.6
import re
import sys

import json

fields = []
for field_pair in sys.argv[1].split(','):
  field_name, value = None, None
  if '=' in field_pair:
    field_name, value = field_pair.split('=')
  else:
    field_name = field_pair
  fields.append((field_name, value))

filehandles = [sys.stdin]
if len(sys.argv) > 2:
  filehandles = []
  for filename in sys.argv[2:]:
    filehandles.append(open(filename))
for fh in filehandles:
  for line in fh:
    j = json.loads(line)
    result = []
    for field_name, value in fields:
      if value is not None:
        if re.search(value, str(j[field_name])):
          print line,
      else:
        field_value = j.get(field_name, '')
        if isinstance(field_value, basestring):
          result.append(field_value.encode('utf-8'))
        else:
          result.append(str(field_value))
    print '\t'.join(result)
