#! /bin/bash

# Configures a variable amount of packet loss on OS X.
#
# Usage:
#
#   Turn on 10% packet loss:
#     sudo packet_loss on 0.10 
#   Turn off packet loss:
#     sudo packet_loss off

if [[ "$1" == "off" ]]
then
  echo "Turning off packet loss"
  ipfw delete 42
  ipfw pipe delete 42
fi

if [[ "$1" == "on" ]]
then
  echo "Turning on packet loss"
  ipfw delete 42
  ipfw pipe delete 42
  ipfw pipe 42 config plr $2
  ipfw add 42 pipe 42 ip from any to any iplen 1000-3000
fi

if [[ "$1" == "show" ]]
then
  ipfw show
  ipfw pipe show
fi
