#! /bin/bash


COUNT=0
while [ "1" ]
do
  echo -n "Run $COUNT..."
  COUNT=$(($COUNT + 1))
  OUTPUT=`nosetests $* 2>&1`
  if [ "$?" == "0" ]
  then
    echo -en "\033[32m"
    echo "OK"
    echo -en "\033[0m"
  else
    echo -en "\033[31m"
    echo "FAILED"
    echo -en "\033[0m"
    echo "$OUTPUT"
  fi
done
